config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  devise_for :users
  get 'main/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "main#index"
  resources :services
  resources :orders, only: [:new, :create, :update, :destroy, :show]
  resources :contacts
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carousel.rb
class Carousel < ApplicationRecord
  has_one_attached :image
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  validates :name, presence: true, length: {minimum: 2}




  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :file, attachment: true
  attribute :sender, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :phone
  validates :phone, :presence => {:message => 'hello world, bad operation!'},
                    :numericality => true,
                    :length => { :minimum => 12, :maximum => 12 }

  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "Сообшение от сайта ITMASTER33",
      to: "egorarbuzov@gmail.com",
      from: %("#{name}" <#{sender}>)
    }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_many_attached :images
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_one_attached :logo
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :picture
  has_many_attached :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         attr_writer :login
     validate :validate_username

     def login
       @login || self.username || self.email
     end

     # app/models/user.rb

       def self.find_for_database_authentication(warden_conditions)
         conditions = warden_conditions.dup
         if (login = conditions.delete(:login))
           where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
         elsif conditions.has_key?(:username) || conditions.has_key?(:email)
           where(conditions.to_h).first
         end
       end
       def validate_username
         if User.where(email: username).exists?
           errors.add(:username, :invalid)
         end
       end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale, :set_variable
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end
  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end
  def default_url_options
    { locale: I18n.locale }
  end
  def set_variable
    @organization = Organization.first
    @a = -1
    @time = Time.now
    @carouseles = Carousel.where(id: 2..100)
  #@carouseles = Carousel.all
    @carousel_active = Carousel.first
  end

  protected
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(params[:contact])
    @contact.sender = 'egoruska85@mail.ru'
    @contact.request = request

    if @contact.deliver
      flash.now[:error] = nil
      redirect_to request.referrer, info: "Отправлено"
    else
      flash.now[:error] != nil


      redirect_to request.referrer, info: "Не отправлено"
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @contact = Contact.new
    @about = About.last
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def new
    @services = Service.all
  end
  def show
    @order = Order.find(params[:id])
    if current_user == nil or @order.user_id != current_user.id
      redirect_to root_path
    end
  end
  def create

    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.save
    flash[:alert] = "User not found."
    redirect_to @order
  end
  private
  def order_params
    params.require(:order).permit(:user_id, :service_id, :phone, :date, :time, :verificate, :done, :defect, :address, :images => [])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services_1 = Service.where(number: 1000...1020)
    @services_2 = Service.where(number: 1021...1040)
  end
  def show
    @service = Service.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/_telegram.html.erb
<a href="https://t.me/itmaster_33" target="_blank" id="telegram-icon">
  <img src="https://telegram.org/img/t_logo.png" alt="Telegram" width="50" height="50">
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if @organization.logo.present? %>
    <%= favicon_link_tag rails_blob_url(@organization.logo) %>
    <% end %>
    <title><%= @organization.name %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'slide', media: 'all' %>
    <%= javascript_include_tag 'slide', 'data-turbolinks-track': 'reload' %>



    <style>
      body {
        background-image: url('/images/digitization-g47f47bac3_1920.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
      }
    </style>
  </head>

  <body>

    <%= yield %>
    <nav class="navbar bg-body-tertiary" style="background: linear-gradient(to left, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0)); height: 53px;">
      <div class="container">
        <ul class="nav ms-auto">
          <%= @organization.name %>&copy; <%= Time.now.year %> <%= t('footer.rights')%>
        </ul>
      </div>
    </nav>
  </body>
</html>

app/views/logo/_logo.html.erb
<%= link_to root_path, class:"nav-link", style:"font-family: bankgothic; font-weight: 900; font-size: 30px; color: blue;" do %>
  <%= image_tag(@organization.logo, alt:"Logo", width:"60", height:"48", class:"d-inline-block align-text-top") %>
  <%= @organization.name %>
<% end %>

app/views/main/_about.html.erb
<div class="container" id="about">
  <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded border border-primary" style="background-color: rgba(255, 255, 255, 0.9);">
    <center><h1 style="font-family: bankgothic;"><%= @about.title %></h1></center>
    <%= simple_format @about.body %>
  </div>
</div>

app/views/main/_carousel.html.erb
<div class="container-fluid">
  <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: rgba(28, 36, 237, 0.5);">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <% @carouseles.each do |i| %>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= @a + i.id %>" aria-label="Slide <%= @a + i.id + 1 %>"></button>
        <% end %>
      </div>
      <div class="carousel-inner container-fluid d-md-block">
        <div class="carousel-item active">
          <%= link_to @carousel_active.link do %>
          <%= image_tag(@carousel_active.image, class:"d-block w-100", alt:"...") %>
          <% end %>
          <div class="carousel-caption d-none d-md-block">
            <h1><%= @carousel_active.title %></h1>
            <p><%= @carousel_active.text %></p>
          </div>
        </div>
        <% @carouseles.each do |carousel| %>
        <div class="carousel-item">
          <%= link_to carousel.link do %>
            <%= image_tag(carousel.image, class:"d-block w-100", alt:"...") %>
          <% end %>
            <div class="carousel-caption d-none d-md-block">
              <h1><%= carousel.title %></h1>
              <p><%= carousel.text %></p>
            </div>
        </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

app/views/main/_contacts.html.erb
<div class="container" id="contacts" >
  <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded border border-primary" style="background-color: rgba(255, 255, 255, 0.9);">
    <center><h1 style="font-family: bankgothic;">Наши контакты</h1></center>

      <div class="row">
        <div class="col-md-6">
          <%= phone_to @about.phone, class:'btn btn-info', style:'max-height: 38px;' do %>
            <p style="font-size: 20px;"><i class="bi bi-telephone-outbound-fill"></i><%= @about.phone %></p>
          <% end %>
          <br><br>
          <%= link_to "https://api.whatsapp.com/send/?phone=(#{@about.whatsapp})", class:"btn btn-success" do %>
            <i class="bi bi-whatsapp">WhatsApp</i>
          <% end %>
          <br><br>
          <%= link_to "https://telegram.me/#{@about.telegram}", class:"btn btn-primary" do %>
            <i class="bi bi-telegram">Telegram</i>
          <% end %>
          <br><br>
          <%= mail_to @about.email, class:"btn btn-primary" do %>
            <i class="bi bi-mail">Эл. почта: <%= @about.email %></i>
          <% end %>
          <br><br>
          <div class="row">
            <div class="col-3">
              <h6>Наш адрес: </h6>
            </div>
            <div class="col-9">
              <h6>
                <%= simple_format @about.address %>
              </h6>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <%= form_for @contact do |f| %>
          <!--</div>-->
          <!--<form method="POST" id="contactForm" name="contactForm" class="contactForm">-->
          <div class="row">
            <center><h1 style="font-family: bankgothic; font-size: 20px;">Обратный связь</h1></center>
            <div class="col-md-6">
              <div class="form-group">
                <!--<label class="label" for="name">Full Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Name">-->
                <%= f.label t('contact.name') %>
                <%= f.text_field :name, class:'form-control', placeholder: t('contact.name')%>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <!--<label class="label" for="email">Email Address</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Email">-->
                <%= f.label t('contact.mail') %>
                <%= f.text_field :email, class:'form-control', placeholder: t('contact.mail')%>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <!--<label class="label" for="subject">Subject</label>
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">-->
                <%= f.label t('contact.sales_phone') %>
                <%= f.text_field :phone, class:'form-control', placeholder: t('contact.sales_phone'), value:'+'%>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <!--<label class="label" for="#">Message</label>
                <textarea name="message" class="form-control" id="message" cols="30" rows="4" placeholder="Message"></textarea>-->
                <%= f.label t('contact.message') %>
                <%= f.text_area :message, class:'form-control', placeholder: t('contact.message'), rows:"6" %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <!--<label class="label" for="#">Message</label>
                <textarea name="message" class="form-control" id="message" cols="30" rows="4" placeholder="Message"></textarea>-->
                <%= f.file_field :file, class:'form-control', type:'file', id:'formFileMultiple', multiple: true %>
              </div>
            </div>
           <br><br>
            <div class="col-md-12">
              <div class="form-group">
                <%= f.submit 'Отправить', class:'btn btn-primary'%>
                <br><br>
                <!--<input type="submit" value="Send Message" class="btn btn-primary">-->
                <div class="submitting"></div>
              </div>
            </div>
          </div>
          <!--</form>-->
          </div>
          <% end %>
        </div>
      </div>

  </div>
</div>

app/views/main/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" style="background: linear-gradient(to right, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0))">
  <div class="container-fluid">
    <%= render 'logo/logo' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'О нас', root_path + '#about', class:"nav-link text-black"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Наши контакты', root_path + '#contacts', class:"nav-link text-black"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Услуги', services_path, class:"nav-link text-black"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Ваша заявка', new_order_path, class:"nav-link text-black" %>
        </li>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><i class="bi bi-person-fill"></i></button>

      </ul>
    </div>
  </div>
</nav>
<%= render '/user/user' %>

app/views/main/_owl.html.erb
<div class="home-slider owl-carousel">
  <% @carouseles.each do |carousel| %>
  <div class="slider-item" style="background-image:url(<%= rails_blob_url(carousel.image)%>);">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-center justify-content-center">
        <div class="col-md-12 ftco-animate">
          <div class="text w-100 text-center">
            <h2><%= carousel.text %></h2>
            <h3 class="mb-3"><%= carousel.title %></h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <style>
  /* Стили для фиксированного значка */
  #telegram-icon {
    position: fixed;           /* фиксируем относительно окна */
    right: 20px;               /* отступ справа */
    bottom: 20px;              /* отступ снизу */
    width: 50px;               /* ширина и высота значка */
    height: 50px;
    cursor: pointer;
    z-index: 1000;             /* чтобы быть поверх других элементов */
    transition: transform 0.3s;
  }

  #telegram-icon:hover {
    transform: scale(1.1);     /* при наведении немного увеличиваем */
  }
</style>
  </head>



  <body>
    <%= render "navbar" %>
    <%= render "carousel" %>
    <%= render "about" %>
    <%= render "contacts" %>
    <%= render "/layouts/telegram" %>


  </body>
</html>




<!-- CSS -->

app/views/orders/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
<%= render 'logo/logo' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'О нас', root_path + '#about', class:"nav-link text-white"%>

        </li>
        <li class="nav-item">
          <%= link_to 'Наши контакты', root_path + '#contacts', class:"nav-link text-white"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Услуги', services_path, class:"nav-link text-white" %>

        </li>


        <li class="nav-item">
          <%= link_to 'Ваша заявка', new_order_path, class:"nav-link active" %>
        </li>
        <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>-->
        <%= render '/user/user' %>
      </ul>
      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>
<br>

app/views/orders/_navbarnew.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to root_path, class:"nav-link", style:"font-family: bankgothic; font-weight: 900; font-size: 20px; color: blue;" do %>
      <%= @organization.name %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Услуги', services_path, class:"nav-link text-white" %>

        </li>
        <li class="nav-item">
          <%= link_to 'Ваша заявка', new_order_path, class:"nav-link active" %>
        </li>
        <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>-->
        <%= render '/user/user' %>
      </ul>
      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>
<br>

app/views/orders/new.html.erb
<%= render '/orders/navbar' %>
<div class="container">
  <center><h1 class="">Ваша заявка</h1></center>

    <%= form_for :order, url: orders_path do |f| %>
      <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white;">
        <%= f.label "Ваша предполагаемая услуга" %>
        <br><br>
        <%= f.select :service_id, options_for_select(@services.collect{ |service| [service.name, service.id] }), {}, {class: "form-control"} %>
      </div>

        <div class="row">
          <div class="col-sm-12 col-lg-6">
            <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white;">
              <%= f.label "Опишите вашу проблему" %>
              <br><br>
              <%= f.text_area :defect, class:"form-control", rows:"6" %>
            </div>
          </div>
          <div class="col-sm-12 col-lg-6">
            <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white; height: 240px;">
              <%= f.label "Укажите ваш телефон" %>
              <br><br>
              <%= f.text_field :phone, value: current_user.phone, class:"form-control" %>
<hr>
              <%= f.label "Укажите ваш адрес" %>
              <br>
              <%= f.text_area :address, value: current_user.address, class:"form-control" %>
            </div>
          </div>
        </div>
        <center>
          <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white; width: 350px;">
            <%= f.label "Можете прикрепить картинки проблемы" %>
            <br><br>
            <%= f.file_field :images, multiple: true, class:'form-control' %>
          </div>
          <%= f.submit 'Отправить заявку', class:"btn btn-success" %>

        </center>





    <% end %>

</div>
<br><br><br>

app/views/orders/show.html.erb
<%= render '/orders/navbarnew' %>
<%= @order.phone %>

app/views/services/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
<%= render 'logo/logo' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'О нас', root_path + '#about', class:"nav-link text-white"%>

        </li>
        <li class="nav-item">
          <%= link_to 'Наши контакты', root_path + '#contacts', class:"nav-link text-white"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Услуги', services_path, class:"nav-link active" %>

        </li>


        <li class="nav-item">
          <%= link_to 'Ваша заявка', new_order_path, class:"nav-link text-white" %>
        </li>
        <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>-->
        <%= render '/user/user' %>
      </ul>
      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>
<br>

app/views/services/_table.html.erb
    <table class="table">
      <thead>
        <tr>
          <center><h3>Компьютеры и ноутбуки</h3></center>
          <hr>
          <th scope="col">Номер услуги</th>
          <th scope="col">Наименование работ</th>
          <th scope="col">Цена за работу</th>

        </tr>
      </thead>
      <tbody>
        <% @services_1.each do |service| %>
        <tr>
          <th scope="row"><%= service.number %></th>
          <td><%= link_to "#{service.name}", service_path(service), class:"nav-link" %></td>
          <td><%= service.price %> &#8381; </td>

        </tr>
        <% end %>

      </tbody>
    </table>

app/views/services/_table2.html.erb
<table class="table">
  <thead>
    <tr>
      <center><h3>Серверное оборудование</h3></center>
      <hr>
      <th scope="col">Номер услуги</th>
      <th scope="col">Наименование работ</th>
      <th scope="col">Цена за работу</th>

    </tr>
  </thead>
  <tbody>
    <% @services_2.each do |service| %>
    <tr>
      <th scope="row"><%= service.number %></th>
      <td><%= link_to "#{service.name}", service_path(service), class:"nav-link" %></td>
      <td><%= service.price %> &#8381; </td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/services/index.html.erb
<%= render '/services/navbar' %>
<center><h1>Услуги и цены</h1></center>
<div class="container">
  <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white;" id="p1" >
    <%= render '/services/table' %>
  </div>
  <hr>
  <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white;" id="p2" >
    <%= render '/services/table2' %>
    
  </div>

</div>

app/views/services/show.html.erb
<head>

</head>
<body>

  <%= render '/services/navbar' %>
  <center>
  <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white; width: 350px;">
      <center><h1>Услуги и цены</h1></center>
  </div>
  </center>
  <div class="container">
    <div class="row">



        <div class="col-12 col-lg-6">
          <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white; min-height: 200px;">
              <b><h5><%= @service.name %></h5></b>
          </div>
        </div>
      <div class="col-12 col-lg-6">
        <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white; min-height: 200px;">
          <%= @service.explanation %>
        </div>
      </div>
    </div>
      <center>
        <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded" style="background: white; width: 360px;">
            <h3>Цена: &nbsp; &nbsp;<span class="badge text-bg-success"><%= @service.price %> &#8381;</span></h3>
        </div>
      </center>


  </div>
</body>

app/views/user/_user.html.erb
<% if current_user == nil %>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
             <%= link_to new_user_session_path, class:'btn btn-success' do %>
              <i class="bi bi-person-check-fill"></i><br>Войти
             <% end %>
          </div>
          <div class="modal-content">
             <%= link_to new_user_registration_path, class:'btn btn-warning' do %>
             <i class="bi bi-person-plus-fill"></i><br>
              Регистрация пользователя
             <% end %>
          </div>
        </div>
      </div>
<% end %>
<% if current_user %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content" style="background: #292929;">
        <center>
          <%= button_to destroy_user_session_path, class:'btn btn-dark', method: :delete do %>
          <i class="bi bi-person-dash"></i><br>Выйти
          <% end %>
        </center>
      </div>
      <div class="modal-content">
        <%= link_to edit_user_registration_path(current_user.id), class:'btn btn-success' do %>
          <i class="bi bi-pencil-fill"></i>
          <br>
          Редактирование пользователя
          <% end %>
      </div>
      <br>
      <% if current_user.admin == true %>
        <div class="modal-content">
          <%= link_to "/rails_admin", class:'btn btn-danger' do %>
            <i class="bi bi-tools"></i>
            <br>
            Админка
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>